[project]
name = "streamlit-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.32.0",
    "pandas>=2.2.0",
    "numpy>=1.26.4",
    "matplotlib>=3.8.2",
]
